eef_ppoint_distance: 0.3
tool_length: 0.5
max_angle: 30
roll_boundaries: [-360, 360]
z_translation_boundaries: [-0.2, 0.3]

backend: "frankr"
frankr:
  robot_name: "panda_arm"
  dynamic_rel: 0.2
  rviz_marker: false
