eef_ppoint_distance: 0.3  # distance from end effector to pivot point
tool_length: 0.5
max_angle: 30  # maximum angle of the 'pitch/yaw' cone
roll_boundaries: [-360, 360]
z_translation_boundaries: [-0.2, 0.3]
clip_to_boundaries: true  # if true, clip outsider points to valid boundaries (throw exceptions otherwise)
move_directly: false  # if true, move to target point on the shortest path. Otherwise do pitch/yaw and z-translation/roll successively (order depends on the relative z-translation)
visualize: true  # if true, publish Marker messages
marker_topic: "/rviz_visual_tools"

backend: "moveit"
#frankr:
#  dynamic_rel: 0.2
#frankx:
#  fci_ip: "192.168.2.155"
#  dynamic_rel: 0.2